name: CI

on:
  pull_request:

permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Lint GitHub Actions
        uses: Funcan/gh-action-lint@781ba972d857b41686756b74d51a1fc00d3aba04 # v1.4.0

      - name: Build
        run: make build

      - name: Format
        run: |
          make fmt
          git diff --exit-code

      - name: Test
        run: make test
